// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lab02;

#nullable disable

namespace lab02.Migrations
{
    [DbContext(typeof(spaceRecord))]
    partial class spaceRecordModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("lab02.peopleInSpace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("message")
                        .HasColumnType("TEXT");

                    b.Property<int?>("number")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PeopleInSpaces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            message = "success",
                            number = 1
                        });
                });

            modelBuilder.Entity("lab02.personInSpace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("craft")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("peopleInSpaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("peopleInSpaceId");

                    b.ToTable("personInSpace");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            craft = "ISS",
                            name = "Mateusz",
                            peopleInSpaceId = 1
                        });
                });

            modelBuilder.Entity("lab02.personInSpace", b =>
                {
                    b.HasOne("lab02.peopleInSpace", "peopleInSpace")
                        .WithMany("people")
                        .HasForeignKey("peopleInSpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("peopleInSpace");
                });

            modelBuilder.Entity("lab02.peopleInSpace", b =>
                {
                    b.Navigation("people");
                });
#pragma warning restore 612, 618
        }
    }
}
